{{- define "app.helm.chart.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-nginx-service"
  labels:
    app: "{{ .Release.Name }}-nginx"
spec:
  selector:
    app: "{{ .Release.Name }}-nginx"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
{{- end -}}